name: WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/wakatime-readme@v1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
